In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# Import packages
import pandas as pd
import numpy as np
import missingno as msno
import seaborn as sns
import matplotlib.pyplot as plt
# Setting the max_columns to 50
pd.set_option('display.max_columns',50)
# Find the file on the sidebar and copy path
fpath = "/content/drive/MyDrive/AXSOSACADEMY/01-Fundamentals/Week04/ames-housing-dojo-prep.csv"
df = pd.read_csv(fpath)
df = df.set_index("PID")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 2930 entries, 907227090 to 902201120
Data columns (total 36 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        2930 non-null   int64
 1   MS Zoning         2930 non-null   object
 2   Lot Frontage      2440 non-null   float64
 3   Lot Area          2930 non-null   int64
 4   Street            2930 non-null   object
 5   Alley             198 non-null    object
 6   Utilities         2930 non-null   object
 7   Neighborhood      2930 non-null   object
 8   Bldg Type         2930 non-null   object
 9   House Style       2930 non-null   object
 10  Overall Qual      2930 non-null   int64
 11  Overall Cond      2930 non-null   int64
 12  Year Built        2930 non-null   int64
 13  Year Remodeled    2930 non-null   int64
 14  Exter Qual        2930 non-null   object
 15  Exter Cond        2930 non-null   object
 16  Bsmt Unf Sqft     2929 non-null   float64
 17  Total Bsmnt Sqft  2929 non-null   float64
 18  Central Air       2930 non-null   object
 19  Living Area Sqft  2930 non-null   float64
 20  Bedroom           2930 non-null   int64
 21  Kitchen           2930 non-null   int64
 22  Total Rooms       2930 non-null   int64
 23  Garage Type       2773 non-null   object
 24  Garage Yr Blt     2770 non-null   float64
 25  Garage Cars       2929 non-null   float64
 26  Garage Area       2929 non-null   float64
 27  Garage Qual       2771 non-null   object
 28  Garage Cond       2771 non-null   object
 29  Paved Drive       2930 non-null   object
 30  Fence             572 non-null    object
 31  SalePrice         2930 non-null   float64
 32  Month             2930 non-null   int64
 33  Year              2930 non-null   int64
 34  Total Half Baths  2925 non-null   float64
 35  Total Full Baths  2928 non-null   float64
dtypes: float64(10), int64(11), object(15)
memory usage: 847.0+ KB

,Unnamed: 0,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Utilities,Neighborhood,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remodeled,Exter Qual,Exter Cond,Bsmt Unf Sqft,Total Bsmnt Sqft,Central Air,Living Area Sqft,Bedroom,Kitchen,Total Rooms,Garage Type,Garage Yr Blt,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Fence,SalePrice,Month,Year,Total Half Baths,Total Full Baths
PID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
907227090,0,RL,60.0,7200,Pave,NaN,AllPub,CollgCr,1Fam,1Story,5,8,1972,1972,TA,TA,427.0,864.0,Y,864.0,3,1,5,Detchd,1977.0,1.0,297.0,TA,TA,Y,MnPrv,119900.0,3,2006,0.0,1.0
527108010,1,RL,134.0,19378,Pave,NaN,AllPub,Gilbert,1Fam,2Story,7,5,2005,2006,Gd,TA,1335.0,1392.0,Y,2462.0,4,1,9,Attchd,2006.0,2.0,576.0,TA,TA,Y,NaN,320000.0,3,2006,1.0,3.0
534275170,2,RL,NaN,12772,Pave,NaN,AllPub,NAmes,1Fam,1Story,6,8,1960,1998,TA,Gd,460.0,958.0,Y,958.0,2,1,5,Attchd,1960.0,1.0,301.0,TA,TA,Y,NaN,151500.0,4,2007,0.0,1.0
528104050,3,RL,114.0,14803,Pave,NaN,AllPub,NridgHt,1Fam,1Story,10,5,2007,2008,Ex,TA,442.0,2078.0,Y,2084.0,2,1,7,Attchd,2007.0,3.0,1220.0,TA,TA,Y,NaN,385000.0,6,2008,0.0,3.0
533206070,4,FV,32.0,3784,Pave,Pave,AllPub,Somerst,TwnhsE,1Story,8,5,2006,2007,Gd,TA,1451.0,1511.0,Y,1565.0,2,1,5,Attchd,2006.0,2.0,476.0,TA,TA,Y,NaN,193800.0,2,2007,0.0,3.0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

##**Train Test Split**

In [ ]:
# The target we are trying to predict
y = df['SalePrice']
# The features we will use to make the prediction
X = df.drop(columns = 'SalePrice')
# Import the TTS from sklearn
# Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
X_train.head()

,Unnamed: 0,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Utilities,Neighborhood,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remodeled,Exter Qual,Exter Cond,Bsmt Unf Sqft,Total Bsmnt Sqft,Central Air,Living Area Sqft,Bedroom,Kitchen,Total Rooms,Garage Type,Garage Yr Blt,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Fence,Month,Year,Total Half Baths,Total Full Baths
PID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
905475520,854,RL,NaN,11515,Pave,NaN,AllPub,Edwards,1Fam,1Story,4,5,1958,1994,TA,TA,0.0,0.0,N,943.0,3,1,5,Detchd,1958.0,1.0,308.0,TA,TA,N,NaN,8,2007,0.0,1.0
909254010,2757,RL,53.0,7155,Pave,NaN,AllPub,Crawfor,1Fam,2Story,7,8,1918,1990,TA,TA,600.0,600.0,Y,1228.0,3,1,6,Detchd,1918.0,1.0,215.0,Fa,TA,Y,MnPrv,5,2009,0.0,1.0
531450090,2820,RL,NaN,7153,Pave,NaN,AllPub,SawyerW,1Fam,1Story,6,5,1991,1991,TA,TA,78.0,1278.0,Y,1294.0,3,1,6,Attchd,1991.0,2.0,496.0,TA,TA,Y,GdWo,6,2008,0.0,3.0
903400040,1201,RL,60.0,13515,Pave,Pave,AllPub,BrkSide,1Fam,2Story,6,6,1919,1950,TA,TA,764.0,764.0,Y,1824.0,3,1,8,Detchd,1940.0,2.0,520.0,TA,TA,N,GdPrv,7,2007,0.0,1.0
527107130,2797,RL,60.0,8400,Pave,NaN,AllPub,Gilbert,1Fam,SLvl,7,5,1996,1997,TA,TA,100.0,384.0,Y,1628.0,3,1,7,BuiltIn,1996.0,2.0,390.0,TA,TA,Y,NaN,6,2009,1.0,2.0

**Pipeline For Preprocessing Numeric Features**

**1) Define the list of features**

In [ ]:
# Defining lists of types of features
num_cols = X_train.select_dtypes("number").columns
num_cols

Index(['Unnamed: 0', 'Lot Frontage', 'Lot Area', 'Overall Qual',
       'Overall Cond', 'Year Built', 'Year Remodeled', 'Bsmt Unf Sqft',
       'Total Bsmnt Sqft', 'Living Area Sqft', 'Bedroom', 'Kitchen',
       'Total Rooms', 'Garage Yr Blt', 'Garage Cars', 'Garage Area', 'Month',
       'Year', 'Total Half Baths', 'Total Full Baths'],
      dtype='object')

In [ ]:
# Null values
X_train[num_cols].isna().sum()

Unnamed: 0            0
Lot Frontage        366
Lot Area              0
Overall Qual          0
Overall Cond          0
Year Built            0
Year Remodeled        0
Bsmt Unf Sqft         0
Total Bsmnt Sqft      0
Living Area Sqft      0
Bedroom               0
Kitchen               0
Total Rooms           0
Garage Yr Blt       125
Garage Cars           1
Garage Area           1
Month                 0
Year                  0
Total Half Baths      3
Total Full Baths      1
dtype: int64

In [ ]:
# Summary stats
X_train[num_cols].describe().round(2)

,Unnamed: 0,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remodeled,Bsmt Unf Sqft,Total Bsmnt Sqft,Living Area Sqft,Bedroom,Kitchen,Total Rooms,Garage Yr Blt,Garage Cars,Garage Area,Month,Year,Total Half Baths,Total Full Baths
count,2197.00,1831.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2072.00,2196.00,2196.00,2197.00,2197.00,2194.00,2196.00
mean,1481.47,69.06,10051.87,6.07,5.56,1970.88,1984.06,559.18,1048.32,1495.06,2.85,1.04,6.43,1978.00,1.76,470.32,6.18,2007.80,0.44,1.98
std,851.73,23.17,7006.81,1.43,1.11,30.42,21.03,436.22,450.04,508.24,0.83,0.21,1.58,25.18,0.77,218.38,2.69,1.32,0.54,0.76
min,0.00,21.00,1300.00,1.00,1.00,1872.00,1950.00,0.00,0.00,334.00,0.00,0.00,2.00,1895.00,0.00,0.00,1.00,2006.00,0.00,1.00
25%,748.00,58.00,7425.00,5.00,5.00,1953.00,1964.00,222.00,784.00,1120.00,2.00,1.00,5.00,1960.00,1.00,312.00,4.00,2007.00,0.00,1.00
50%,1485.00,68.00,9405.00,6.00,5.00,1972.00,1993.00,467.00,982.00,1440.00,3.00,1.00,6.00,1979.00,2.00,474.00,6.00,2008.00,0.00,2.00
75%,2217.00,80.00,11600.00,7.00,6.00,2001.00,2004.00,798.00,1288.00,1734.00,3.00,1.00,7.00,2002.00,2.00,576.00,8.00,2009.00,1.00,2.00
max,2958.00,313.00,164660.00,10.00,9.00,2010.00,2010.00,2336.00,6110.00,5642.00,6.00,3.00,15.00,2010.00,5.00,1488.00,12.00,2010.00,3.00,6.00

##**2) Instantiate the Transformers**

In [ ]:
# instantiate preprocessors
impute_median = SimpleImputer(strategy='median')
scaler = StandardScaler()

##**3) Instantiate the Pipeline**

In [ ]:
num_pipe = make_pipeline(impute_median, scaler)
num_pipe

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('standardscaler', StandardScaler())])

##**4) Fit the Pipeline on the Training Data**

In [ ]:
# Fit the pipeline on the numeric training data
num_pipe.fit(X_train[num_cols])

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                ('standardscaler', StandardScaler())])

##**5a) Transform the Training Data**

In [ ]:
# Transform the training data
X_train_num_tf = num_pipe.transform(X_train[num_cols])
X_train_num_tf.head()

,Unnamed: 0,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remodeled,Bsmt Unf Sqft,Total Bsmnt Sqft,Living Area Sqft,Bedroom,Kitchen,Total Rooms,Garage Yr Blt,Garage Cars,Garage Area,Month,Year,Total Half Baths,Total Full Baths
PID,,,,,,,,,,,,,,,,,,,,
905475520,-0.736868,-0.041873,0.208863,-1.453681,-0.502192,-0.423561,0.472590,-1.282165,-2.329907,-1.086450,0.183403,-0.203499,-0.909803,-0.820130,-0.989438,-0.743628,0.674753,-0.605551,-0.807982,-1.289301
909254010,1.497906,-0.750990,-0.413530,0.648845,2.193205,-1.738890,0.282376,0.093593,-0.996395,-0.525568,0.183403,-0.203499,-0.275453,-2.455923,-0.989438,-1.169681,-0.439858,0.908844,-0.807982,-1.289301
531450090,1.571890,-0.041873,-0.413816,-0.051997,-0.502192,0.661586,0.329930,-1.103317,0.510475,-0.395679,0.183403,-0.203499,-0.275453,0.529399,0.313016,0.117642,-0.068321,0.151646,-0.807982,1.343221
903400040,-0.329371,-0.420069,0.494365,-0.051997,0.396274,-1.706007,-1.619758,0.469633,-0.631901,0.647364,0.183403,-0.203499,0.993247,-1.556237,0.313016,0.227591,0.303216,-0.605551,-0.807982,-1.289301
527107130,1.544880,-0.420069,-0.235806,0.648845,-0.502192,0.826002,0.615250,-1.052872,-1.476459,0.261635,0.183403,-0.203499,0.358897,0.733873,0.313016,-0.367968,-0.068321,0.908844,1.050800,0.026960

In [ ]:
# Confirming there are 0 null values

X_train_num_tf.isna().sum().sum()

np.int64(0)

In [ ]:
# Confirming the means are ~0 and std is 1

X_train_num_tf.describe().round(2)

,Unnamed: 0,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remodeled,Bsmt Unf Sqft,Total Bsmnt Sqft,Living Area Sqft,Bedroom,Kitchen,Total Rooms,Garage Yr Blt,Garage Cars,Garage Area,Month,Year,Total Half Baths,Total Full Baths
count,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00,2197.00
mean,0.00,-0.00,0.00,-0.00,-0.00,-0.00,-0.00,-0.00,-0.00,0.00,0.00,-0.00,0.00,-0.00,0.00,0.00,-0.00,0.00,0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.74,-2.26,-1.25,-3.56,-4.10,-3.25,-1.62,-1.28,-2.33,-2.28,-3.45,-5.01,-2.81,-3.40,-2.29,-2.15,-1.93,-1.36,-0.81,-1.29
25%,-0.86,-0.42,-0.37,-0.75,-0.50,-0.59,-0.95,-0.77,-0.59,-0.74,-1.03,-0.20,-0.91,-0.70,-0.99,-0.73,-0.81,-0.61,-0.81,-1.29
50%,0.00,-0.04,-0.09,-0.05,-0.50,0.04,0.43,-0.21,-0.15,-0.11,0.18,-0.20,-0.28,0.04,0.31,0.02,-0.07,0.15,-0.81,0.03
75%,0.86,0.43,0.22,0.65,0.40,0.99,0.95,0.55,0.53,0.47,0.18,-0.20,0.36,0.94,0.31,0.48,0.67,0.91,1.05,0.03
max,1.73,11.54,22.07,2.75,3.09,1.29,1.23,4.07,11.25,8.16,3.81,9.41,5.43,1.31,4.22,4.66,2.16,1.67,4.77,5.29

##**5b) Transform the Testing Data**

In [ ]:
# Transform the testing data
X_test_num_tf = num_pipe.transform(X_test[num_cols])
X_test_num_tf.head()

,Unnamed: 0,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remodeled,Bsmt Unf Sqft,Total Bsmnt Sqft,Living Area Sqft,Bedroom,Kitchen,Total Rooms,Garage Yr Blt,Garage Cars,Garage Area,Month,Year,Total Half Baths,Total Full Baths
PID,,,,,,,,,,,,,,,,,,,,
535477060,-0.128558,0.005401,-0.351434,-0.051997,-0.502192,-0.160495,-0.858904,-0.942812,-0.863043,-0.289407,0.183403,-0.203499,-0.275453,-0.492972,0.313016,-0.079351,0.303216,-1.362748,1.050800,-1.289301
535302140,1.068097,-0.041873,0.388586,-0.752839,-0.502192,-0.587977,-1.477098,-0.750206,-0.142946,-1.072674,-1.026618,-0.203499,-0.909803,-1.024604,0.313016,-0.322156,0.303216,0.151646,-0.807982,-1.289301
907290090,1.605946,0.289048,-0.043092,0.648845,-0.502192,0.957535,0.805463,2.455311,1.292802,0.265571,0.183403,-0.203499,-0.275453,0.897452,0.313016,-0.088513,1.417827,0.908844,-0.807982,0.026960
528138030,0.780383,0.761792,0.267248,2.050529,-0.502192,1.121951,1.043230,-0.876317,0.281555,1.631367,1.393425,-0.203499,2.896296,1.101927,1.615469,1.217135,0.303216,-1.362748,-0.807982,2.659482
908275280,0.092218,-0.467343,0.915622,-0.752839,1.294739,-0.522210,-1.381991,0.588866,-0.516330,-0.200847,0.183403,-0.203499,0.993247,-0.942815,-0.989438,-0.780278,-0.811395,0.151646,1.050800,-1.289301

In [ ]:
# Confirming there are 0 null values
X_test_num_tf.isna().sum().sum()

np.int64(0)

In [ ]:
# Confirming the means are ~0 and std is 1
X_test_num_tf.describe().round(2)

,Unnamed: 0,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remodeled,Bsmt Unf Sqft,Total Bsmnt Sqft,Living Area Sqft,Bedroom,Kitchen,Total Rooms,Garage Yr Blt,Garage Cars,Garage Area,Month,Year,Total Half Baths,Total Full Baths
count,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00,733.00
mean,-0.01,0.03,0.05,0.06,0.02,0.06,0.04,0.00,0.03,0.04,0.03,0.04,0.02,0.01,0.04,0.05,0.05,-0.03,0.04,0.10
std,1.01,1.03,1.44,0.95,0.99,0.98,0.97,1.03,0.91,0.98,1.01,1.11,0.99,1.00,0.96,0.94,1.03,0.99,1.06,0.96
min,-1.73,-2.26,-1.22,-2.86,-3.20,-2.99,-1.62,-1.28,-2.33,-1.88,-3.45,-5.01,-2.18,-3.19,-2.29,-2.15,-1.93,-1.36,-0.81,-2.61
25%,-0.90,-0.42,-0.36,-0.75,-0.50,-0.52,-0.81,-0.79,-0.55,-0.69,-1.03,-0.20,-0.91,-0.57,-0.99,-0.51,-0.81,-0.61,-0.81,0.03
50%,-0.02,-0.04,-0.08,-0.05,-0.50,0.17,0.43,-0.24,-0.07,-0.08,0.18,-0.20,-0.28,0.04,0.31,0.06,-0.07,0.15,-0.81,0.03
75%,0.88,0.53,0.19,0.65,0.40,0.99,0.95,0.57,0.61,0.54,0.18,-0.20,0.36,0.94,0.31,0.48,0.67,0.91,1.05,0.03
max,1.73,5.96,29.29,2.75,3.09,1.25,1.23,3.45,4.64,6.26,6.23,9.41,4.80,1.27,2.92,3.87,2.16,1.67,6.63,5.29

##**Pipeline For Preprocessing Ordinal Features**

##**1) Define a List of Features**

In [ ]:
# Defining lists of ordinal features
ord_cols = ['Exter Qual','Exter Cond', "Garage Qual",'Garage Cond']

##**2) Instantiate the Transformers**

In [ ]:
# Specifying the order of categories in quality/condition columns
impute_na_ord = SimpleImputer(strategy='constant', fill_value='NA')
## Making the OrdinalEncoder
# Specifying order of categories for our  Ordinal Qual/Cond Columms
qual_cond_order = ['NA','Po', 'Fa', 'TA', 'Gd', 'Ex']
# Making the list of order lists for OrdinalEncoder
ordinal_category_orders = [qual_cond_order, qual_cond_order, qual_cond_order, qual_cond_order]

ord_encoder = OrdinalEncoder(categories=ordinal_category_orders)
# Making a final scaler to scale category #'s
scaler_ord = StandardScaler()

##**3) Instantiate the Pipeline**

In [ ]:
# Making an ord_pipe
ord_pipe = make_pipeline(impute_na_ord, ord_encoder, scaler_ord)
ord_pipe

Pipeline(steps=[('simpleimputer',
                 SimpleImputer(fill_value='NA', strategy='constant')),
                ('ordinalencoder',
                 OrdinalEncoder(categories=[['NA', 'Po', 'Fa', 'TA', 'Gd',
                                             'Ex'],
                                            ['NA', 'Po', 'Fa', 'TA', 'Gd',
                                             'Ex'],
                                            ['NA', 'Po', 'Fa', 'TA', 'Gd',
                                             'Ex'],
                                            ['NA', 'Po', 'Fa', 'TA', 'Gd',
                                             'Ex']])),
                ('standardscaler', StandardScaler())])

##**4) Fit on the Training Data Only**

In [ ]:
# Fit the pipeline on the training data
ord_pipe.fit(X_train[ord_cols])

Pipeline(steps=[('simpleimputer',
                 SimpleImputer(fill_value='NA', strategy='constant')),
                ('ordinalencoder',
                 OrdinalEncoder(categories=[['NA', 'Po', 'Fa', 'TA', 'Gd',
                                             'Ex'],
                                            ['NA', 'Po', 'Fa', 'TA', 'Gd',
                                             'Ex'],
                                            ['NA', 'Po', 'Fa', 'TA', 'Gd',
                                             'Ex'],
                                            ['NA', 'Po', 'Fa', 'TA', 'Gd',
                                             'Ex']])),
                ('standardscaler', StandardScaler())])

##**5a) and 5b) Transform the Train and Test Data**

In [ ]:
# Transform the training and test data
X_train_ord_tf = ord_pipe.transform(X_train[ord_cols])
X_test_ord_tf = ord_pipe.transform(X_test[ord_cols])
X_train_ord_tf.head()

           Exter Qual  Exter Cond  Garage Qual  Garage Cond
PID
905475520   -0.679141   -0.227105     0.282215     0.272525
909254010   -0.679141   -0.227105    -1.092567     0.272525
531450090   -0.679141   -0.227105     0.282215     0.272525
903400040   -0.679141   -0.227105     0.282215     0.272525
527107130   -0.679141   -0.227105     0.282215     0.272525

#**Pipeline For Preprocessing Nominal Features**

##**1) Define a List of Features**

In [ ]:
# Defining list of nominal features
ohe_cols = X_train.select_dtypes('object').drop(columns=ord_cols).columns

##**2) Instantiate Transformers**

In [ ]:
# Instantiate the individual preprocessors
impute_na = SimpleImputer(strategy='constant', fill_value = "NA")
ohe_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

##**3) Instantiate the Pipeline**

In [ ]:
# Instantiate the pipeline
ohe_pipe = make_pipeline(impute_na, ohe_encoder)
ohe_pipe

Pipeline(steps=[('simpleimputer',
                 SimpleImputer(fill_value='NA', strategy='constant')),
                ('onehotencoder',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

##**4) Fit on the Training Data Only**

In [ ]:
# Fit the pipeline on the training data
ohe_pipe.fit(X_train[ohe_cols])

Pipeline(steps=[('simpleimputer',
                 SimpleImputer(fill_value='NA', strategy='constant')),
                ('onehotencoder',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

##**5a) and 5b) Transform the Training and Test Data**

In [ ]:
#Transform the training and test data
X_train_ohe_tf = ohe_pipe.transform(X_train[ohe_cols])
X_test_ohe_tf = ohe_pipe.transform(X_test[ohe_cols])
X_train_ohe_tf.head()

,MS Zoning_A (agr),MS Zoning_C (all),MS Zoning_FV,MS Zoning_I (all),MS Zoning_RH,MS Zoning_RL,MS Zoning_RM,Street_Grvl,Street_Pave,Alley_Grvl,Alley_NA,Alley_Pave,Utilities_AllPub,Utilities_NoSewr,Neighborhood_Blmngtn,Neighborhood_Blueste,Neighborhood_BrDale,Neighborhood_BrkSide,Neighborhood_ClearCr,Neighborhood_CollgCr,Neighborhood_Crawfor,Neighborhood_Edwards,Neighborhood_Gilbert,Neighborhood_Greens,Neighborhood_GrnHill,...,House Style_1.5Fin,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl,Central Air_N,Central Air_Y,Garage Type_2Types,Garage Type_Attchd,Garage Type_Basment,Garage Type_BuiltIn,Garage Type_CarPort,Garage Type_Detchd,Garage Type_NA,Paved Drive_N,Paved Drive_P,Paved Drive_Y,Fence_GdPrv,Fence_GdWo,Fence_MnPrv,Fence_MnWw,Fence_NA
PID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
905475520,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
909254010,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
531450090,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
903400040,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
527107130,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

##**Combining Our Processed Data**

In [ ]:
# re-combine the 3 dataframes of training data
X_train_tf = pd.concat([X_train_num_tf, X_train_ord_tf,
                               X_train_ohe_tf], axis=1)
X_train_tf.info()
X_train_tf.head()

<class 'pandas.core.frame.DataFrame'>
Index: 2197 entries, 905475520 to 909131170
Data columns (total 96 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            2197 non-null   float64
 1   Lot Frontage          2197 non-null   float64
 2   Lot Area              2197 non-null   float64
 3   Overall Qual          2197 non-null   float64
 4   Overall Cond          2197 non-null   float64
 5   Year Built            2197 non-null   float64
 6   Year Remodeled        2197 non-null   float64
 7   Bsmt Unf Sqft         2197 non-null   float64
 8   Total Bsmnt Sqft      2197 non-null   float64
 9   Living Area Sqft      2197 non-null   float64
 10  Bedroom               2197 non-null   float64
 11  Kitchen               2197 non-null   float64
 12  Total Rooms           2197 non-null   float64
 13  Garage Yr Blt         2197 non-null   float64
 14  Garage Cars           2197 non-null   float64
 15  Garage Area           2197 non-null   float64
 16  Month                 2197 non-null   float64
 17  Year                  2197 non-null   float64
 18  Total Half Baths      2197 non-null   float64
 19  Total Full Baths      2197 non-null   float64
 20  Exter Qual            2197 non-null   float64
 21  Exter Cond            2197 non-null   float64
 22  Garage Qual           2197 non-null   float64
 23  Garage Cond           2197 non-null   float64
 24  MS Zoning_A (agr)     2197 non-null   float64
 25  MS Zoning_C (all)     2197 non-null   float64
 26  MS Zoning_FV          2197 non-null   float64
 27  MS Zoning_I (all)     2197 non-null   float64
 28  MS Zoning_RH          2197 non-null   float64
 29  MS Zoning_RL          2197 non-null   float64
 30  MS Zoning_RM          2197 non-null   float64
 31  Street_Grvl           2197 non-null   float64
 32  Street_Pave           2197 non-null   float64
 33  Alley_Grvl            2197 non-null   float64
 34  Alley_NA              2197 non-null   float64
 35  Alley_Pave            2197 non-null   float64
 36  Utilities_AllPub      2197 non-null   float64
 37  Utilities_NoSewr      2197 non-null   float64
 38  Neighborhood_Blmngtn  2197 non-null   float64
 39  Neighborhood_Blueste  2197 non-null   float64
 40  Neighborhood_BrDale   2197 non-null   float64
 41  Neighborhood_BrkSide  2197 non-null   float64
 42  Neighborhood_ClearCr  2197 non-null   float64
 43  Neighborhood_CollgCr  2197 non-null   float64
 44  Neighborhood_Crawfor  2197 non-null   float64
 45  Neighborhood_Edwards  2197 non-null   float64
 46  Neighborhood_Gilbert  2197 non-null   float64
 47  Neighborhood_Greens   2197 non-null   float64
 48  Neighborhood_GrnHill  2197 non-null   float64
 49  Neighborhood_IDOTRR   2197 non-null   float64
 50  Neighborhood_Landmrk  2197 non-null   float64
 51  Neighborhood_MeadowV  2197 non-null   float64
 52  Neighborhood_Mitchel  2197 non-null   float64
 53  Neighborhood_NAmes    2197 non-null   float64
 54  Neighborhood_NPkVill  2197 non-null   float64
 55  Neighborhood_NWAmes   2197 non-null   float64
 56  Neighborhood_NoRidge  2197 non-null   float64
 57  Neighborhood_NridgHt  2197 non-null   float64
 58  Neighborhood_OldTown  2197 non-null   float64
 59  Neighborhood_SWISU    2197 non-null   float64
 60  Neighborhood_Sawyer   2197 non-null   float64
 61  Neighborhood_SawyerW  2197 non-null   float64
 62  Neighborhood_Somerst  2197 non-null   float64
 63  Neighborhood_StoneBr  2197 non-null   float64
 64  Neighborhood_Timber   2197 non-null   float64
 65  Neighborhood_Veenker  2197 non-null   float64
 66  Bldg Type_1Fam        2197 non-null   float64
 67  Bldg Type_2fmCon      2197 non-null   float64
 68  Bldg Type_Duplex      2197 non-null   float64
 69  Bldg Type_Twnhs       2197 non-null   float64
 70  Bldg Type_TwnhsE      2197 non-null   float64
 71  House Style_1.5Fin    2197 non-null   float64
 72  House Style_1.5Unf    2197 non-null   float64
 73  House Style_1Story    2197 non-null   float64
 74  House Style_2.5Fin    2197 non-null   float64
 75  House Style_2.5Unf    2197 non-null   float64
 76  House Style_2Story    2197 non-null   float64
 77  House Style_SFoyer    2197 non-null   float64
 78  House Style_SLvl      2197 non-null   float64
 79  Central Air_N         2197 non-null   float64
 80  Central Air_Y         2197 non-null   float64
 81  Garage Type_2Types    2197 non-null   float64
 82  Garage Type_Attchd    2197 non-null   float64
 83  Garage Type_Basment   2197 non-null   float64
 84  Garage Type_BuiltIn   2197 non-null   float64
 85  Garage Type_CarPort   2197 non-null   float64
 86  Garage Type_Detchd    2197 non-null   float64
 87  Garage Type_NA        2197 non-null   float64
 88  Paved Drive_N         2197 non-null   float64
 89  Paved Drive_P         2197 non-null   float64
 90  Paved Drive_Y         2197 non-null   float64
 91  Fence_GdPrv           2197 non-null   float64
 92  Fence_GdWo            2197 non-null   float64
 93  Fence_MnPrv           2197 non-null   float64
 94  Fence_MnWw            2197 non-null   float64
 95  Fence_NA              2197 non-null   float64
dtypes: float64(96)
memory usage: 1.6 MB

,Unnamed: 0,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remodeled,Bsmt Unf Sqft,Total Bsmnt Sqft,Living Area Sqft,Bedroom,Kitchen,Total Rooms,Garage Yr Blt,Garage Cars,Garage Area,Month,Year,Total Half Baths,Total Full Baths,Exter Qual,Exter Cond,Garage Qual,Garage Cond,MS Zoning_A (agr),...,House Style_1.5Fin,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl,Central Air_N,Central Air_Y,Garage Type_2Types,Garage Type_Attchd,Garage Type_Basment,Garage Type_BuiltIn,Garage Type_CarPort,Garage Type_Detchd,Garage Type_NA,Paved Drive_N,Paved Drive_P,Paved Drive_Y,Fence_GdPrv,Fence_GdWo,Fence_MnPrv,Fence_MnWw,Fence_NA
PID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
905475520,-0.736868,-0.041873,0.208863,-1.453681,-0.502192,-0.423561,0.472590,-1.282165,-2.329907,-1.086450,0.183403,-0.203499,-0.909803,-0.820130,-0.989438,-0.743628,0.674753,-0.605551,-0.807982,-1.289301,-0.679141,-0.227105,0.282215,0.272525,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
909254010,1.497906,-0.750990,-0.413530,0.648845,2.193205,-1.738890,0.282376,0.093593,-0.996395,-0.525568,0.183403,-0.203499,-0.275453,-2.455923,-0.989438,-1.169681,-0.439858,0.908844,-0.807982,-1.289301,-0.679141,-0.227105,-1.092567,0.272525,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
531450090,1.571890,-0.041873,-0.413816,-0.051997,-0.502192,0.661586,0.329930,-1.103317,0.510475,-0.395679,0.183403,-0.203499,-0.275453,0.529399,0.313016,0.117642,-0.068321,0.151646,-0.807982,1.343221,-0.679141,-0.227105,0.282215,0.272525,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
903400040,-0.329371,-0.420069,0.494365,-0.051997,0.396274,-1.706007,-1.619758,0.469633,-0.631901,0.647364,0.183403,-0.203499,0.993247,-1.556237,0.313016,0.227591,0.303216,-0.605551,-0.807982,-1.289301,-0.679141,-0.227105,0.282215,0.272525,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
527107130,1.544880,-0.420069,-0.235806,0.648845,-0.502192,0.826002,0.615250,-1.052872,-1.476459,0.261635,0.183403,-0.203499,0.358897,0.733873,0.313016,-0.367968,-0.068321,0.908844,1.050800,0.026960,-0.679141,-0.227105,0.282215,0.272525,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
# re-combine the 3 dataframes of testing data
X_test_tf = pd.concat([X_test_num_tf, X_test_ord_tf,
                               X_test_ohe_tf], axis=1)
X_test_tf.info()
X_test_tf.head()

<class 'pandas.core.frame.DataFrame'>
Index: 733 entries, 535477060 to 923203140
Data columns (total 96 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            733 non-null    float64
 1   Lot Frontage          733 non-null    float64
 2   Lot Area              733 non-null    float64
 3   Overall Qual          733 non-null    float64
 4   Overall Cond          733 non-null    float64
 5   Year Built            733 non-null    float64
 6   Year Remodeled        733 non-null    float64
 7   Bsmt Unf Sqft         733 non-null    float64
 8   Total Bsmnt Sqft      733 non-null    float64
 9   Living Area Sqft      733 non-null    float64
 10  Bedroom               733 non-null    float64
 11  Kitchen               733 non-null    float64
 12  Total Rooms           733 non-null    float64
 13  Garage Yr Blt         733 non-null    float64
 14  Garage Cars           733 non-null    float64
 15  Garage Area           733 non-null    float64
 16  Month                 733 non-null    float64
 17  Year                  733 non-null    float64
 18  Total Half Baths      733 non-null    float64
 19  Total Full Baths      733 non-null    float64
 20  Exter Qual            733 non-null    float64
 21  Exter Cond            733 non-null    float64
 22  Garage Qual           733 non-null    float64
 23  Garage Cond           733 non-null    float64
 24  MS Zoning_A (agr)     733 non-null    float64
 25  MS Zoning_C (all)     733 non-null    float64
 26  MS Zoning_FV          733 non-null    float64
 27  MS Zoning_I (all)     733 non-null    float64
 28  MS Zoning_RH          733 non-null    float64
 29  MS Zoning_RL          733 non-null    float64
 30  MS Zoning_RM          733 non-null    float64
 31  Street_Grvl           733 non-null    float64
 32  Street_Pave           733 non-null    float64
 33  Alley_Grvl            733 non-null    float64
 34  Alley_NA              733 non-null    float64
 35  Alley_Pave            733 non-null    float64
 36  Utilities_AllPub      733 non-null    float64
 37  Utilities_NoSewr      733 non-null    float64
 38  Neighborhood_Blmngtn  733 non-null    float64
 39  Neighborhood_Blueste  733 non-null    float64
 40  Neighborhood_BrDale   733 non-null    float64
 41  Neighborhood_BrkSide  733 non-null    float64
 42  Neighborhood_ClearCr  733 non-null    float64
 43  Neighborhood_CollgCr  733 non-null    float64
 44  Neighborhood_Crawfor  733 non-null    float64
 45  Neighborhood_Edwards  733 non-null    float64
 46  Neighborhood_Gilbert  733 non-null    float64
 47  Neighborhood_Greens   733 non-null    float64
 48  Neighborhood_GrnHill  733 non-null    float64
 49  Neighborhood_IDOTRR   733 non-null    float64
 50  Neighborhood_Landmrk  733 non-null    float64
 51  Neighborhood_MeadowV  733 non-null    float64
 52  Neighborhood_Mitchel  733 non-null    float64
 53  Neighborhood_NAmes    733 non-null    float64
 54  Neighborhood_NPkVill  733 non-null    float64
 55  Neighborhood_NWAmes   733 non-null    float64
 56  Neighborhood_NoRidge  733 non-null    float64
 57  Neighborhood_NridgHt  733 non-null    float64
 58  Neighborhood_OldTown  733 non-null    float64
 59  Neighborhood_SWISU    733 non-null    float64
 60  Neighborhood_Sawyer   733 non-null    float64
 61  Neighborhood_SawyerW  733 non-null    float64
 62  Neighborhood_Somerst  733 non-null    float64
 63  Neighborhood_StoneBr  733 non-null    float64
 64  Neighborhood_Timber   733 non-null    float64
 65  Neighborhood_Veenker  733 non-null    float64
 66  Bldg Type_1Fam        733 non-null    float64
 67  Bldg Type_2fmCon      733 non-null    float64
 68  Bldg Type_Duplex      733 non-null    float64
 69  Bldg Type_Twnhs       733 non-null    float64
 70  Bldg Type_TwnhsE      733 non-null    float64
 71  House Style_1.5Fin    733 non-null    float64
 72  House Style_1.5Unf    733 non-null    float64
 73  House Style_1Story    733 non-null    float64
 74  House Style_2.5Fin    733 non-null    float64
 75  House Style_2.5Unf    733 non-null    float64
 76  House Style_2Story    733 non-null    float64
 77  House Style_SFoyer    733 non-null    float64
 78  House Style_SLvl      733 non-null    float64
 79  Central Air_N         733 non-null    float64
 80  Central Air_Y         733 non-null    float64
 81  Garage Type_2Types    733 non-null    float64
 82  Garage Type_Attchd    733 non-null    float64
 83  Garage Type_Basment   733 non-null    float64
 84  Garage Type_BuiltIn   733 non-null    float64
 85  Garage Type_CarPort   733 non-null    float64
 86  Garage Type_Detchd    733 non-null    float64
 87  Garage Type_NA        733 non-null    float64
 88  Paved Drive_N         733 non-null    float64
 89  Paved Drive_P         733 non-null    float64
 90  Paved Drive_Y         733 non-null    float64
 91  Fence_GdPrv           733 non-null    float64
 92  Fence_GdWo            733 non-null    float64
 93  Fence_MnPrv           733 non-null    float64
 94  Fence_MnWw            733 non-null    float64
 95  Fence_NA              733 non-null    float64
dtypes: float64(96)
memory usage: 555.5 KB

,Unnamed: 0,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remodeled,Bsmt Unf Sqft,Total Bsmnt Sqft,Living Area Sqft,Bedroom,Kitchen,Total Rooms,Garage Yr Blt,Garage Cars,Garage Area,Month,Year,Total Half Baths,Total Full Baths,Exter Qual,Exter Cond,Garage Qual,Garage Cond,MS Zoning_A (agr),...,House Style_1.5Fin,House Style_1.5Unf,House Style_1Story,House Style_2.5Fin,House Style_2.5Unf,House Style_2Story,House Style_SFoyer,House Style_SLvl,Central Air_N,Central Air_Y,Garage Type_2Types,Garage Type_Attchd,Garage Type_Basment,Garage Type_BuiltIn,Garage Type_CarPort,Garage Type_Detchd,Garage Type_NA,Paved Drive_N,Paved Drive_P,Paved Drive_Y,Fence_GdPrv,Fence_GdWo,Fence_MnPrv,Fence_MnWw,Fence_NA
PID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
535477060,-0.128558,0.005401,-0.351434,-0.051997,-0.502192,-0.160495,-0.858904,-0.942812,-0.863043,-0.289407,0.183403,-0.203499,-0.275453,-0.492972,0.313016,-0.079351,0.303216,-1.362748,1.050800,-1.289301,-0.679141,-0.227105,0.282215,0.272525,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
535302140,1.068097,-0.041873,0.388586,-0.752839,-0.502192,-0.587977,-1.477098,-0.750206,-0.142946,-1.072674,-1.026618,-0.203499,-0.909803,-1.024604,0.313016,-0.322156,0.303216,0.151646,-0.807982,-1.289301,-0.679141,-0.227105,0.282215,0.272525,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
907290090,1.605946,0.289048,-0.043092,0.648845,-0.502192,0.957535,0.805463,2.455311,1.292802,0.265571,0.183403,-0.203499,-0.275453,0.897452,0.313016,-0.088513,1.417827,0.908844,-0.807982,0.026960,1.029992,-0.227105,0.282215,0.272525,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
528138030,0.780383,0.761792,0.267248,2.050529,-0.502192,1.121951,1.043230,-0.876317,0.281555,1.631367,1.393425,-0.203499,2.896296,1.101927,1.615469,1.217135,0.303216,-1.362748,-0.807982,2.659482,2.739125,-0.227105,0.282215,0.272525,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
908275280,0.092218,-0.467343,0.915622,-0.752839,1.294739,-0.522210,-1.381991,0.588866,-0.516330,-0.200847,0.183403,-0.203499,0.993247,-0.942815,-0.989438,-0.780278,-0.811395,0.151646,1.050800,-1.289301,-0.679141,2.426881,0.282215,0.272525,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0