#**Imports and Custom Functions**

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor # NEW
from sklearn import set_config
set_config(transform_output='pandas')

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
def regression_metrics(y_true, y_pred, label='', verbose = True, output_dict=False):
  # Get metrics
  mae = mean_absolute_error(y_true, y_pred)
  mse = mean_squared_error(y_true, y_pred)
  rmse = mean_squared_error(y_true, y_pred)
  r_squared = r2_score(y_true, y_pred)
  if verbose == True:
    # Print Result with Label and Header
    header = "-"*60
    print(header, f"Regression Metrics: {label}", header, sep='\n')
    print(f"- MAE = {mae:,.3f}")
    print(f"- MSE = {mse:,.3f}")
    print(f"- RMSE = {rmse:,.3f}")
    print(f"- R^2 = {r_squared:,.3f}")
  if output_dict == True:
      metrics = {'Label':label, 'MAE':mae,
                 'MSE':mse, 'RMSE':rmse, 'R^2':r_squared}
      return metrics
def evaluate_regression(reg, X_train, y_train, X_test, y_test, verbose = True,
                        output_frame=False):
  # Get predictions for training data
  y_train_pred = reg.predict(X_train)
  # Call the helper function to obtain regression metrics for training data
  results_train = regression_metrics(y_train, y_train_pred, verbose = verbose,
                                     output_dict=output_frame,
                                     label='Training Data')
  print()
  # Get predictions for test data
  y_test_pred = reg.predict(X_test)
  # Call the helper function to obtain regression metrics for test data
  results_test = regression_metrics(y_test, y_test_pred, verbose = verbose,
                                  output_dict=output_frame,
                                    label='Test Data' )
  # Store results in a dataframe if ouput_frame is True
  if output_frame:
    results_df = pd.DataFrame([results_train,results_test])
    # Set the label as the index
    results_df = results_df.set_index('Label')
    # Set index.name to none to get a cleaner looking result
    results_df.index.name=None
    # Return the dataframe
    return results_df.round(3)

**Load the Dataset**

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Using the recommended file structure.
fpath = "/content/drive/MyDrive/AXSOSACADEMY/02-MachineLearning/Week06/auto_mpg_dirty.csv"
df = pd.read_csv(fpath)
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        355 non-null    float64
 5   acceleration  375 non-null    float64
 6   model year    398 non-null    int64
 7   origin        333 non-null    object
 8   car name      398 non-null    object
dtypes: float64(5), int64(2), object(2)
memory usage: 28.1+ KB

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130.0,3504.0,12.0,70,America,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,America,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,America,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,America,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,America,ford torino

#**Create Preprocessing Object**

**Define X and y and Train Test Split**

In [ ]:
# Arrange Data into Features Matrix and Target Vector
y = df['mpg']
X = df.drop(columns = ['mpg','car name'])
# Split the data for validation
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

**Check for Null Values**

In [ ]:
# Check for null values
X_train.isna().sum()

cylinders        0
displacement     0
horsepower       5
weight          30
acceleration    19
model year       0
origin          47
dtype: int64

**Check for Inconsistent Values in Categorical Columns**

In [ ]:
# Check for inconsitent values in categorical columns
X_train['origin'].value_counts()

origin
America    163
Asia        48
Europe      40
Name: count, dtype: int64

##**Preprocessing Pipeline for Categorical Features**

In [ ]:
# Saving list of categorical columns
cat_cols = X_train.select_dtypes('object').columns
# Constructing categorical preprocessing objects
cat_imputer = SimpleImputer(strategy='constant', fill_value='MISSING')
ohe_encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
cat_pipe = make_pipeline(cat_imputer,ohe_encoder)
cat_tuple = ('cat',cat_pipe, cat_cols)
cat_tuple

('cat',
 Pipeline(steps=[('simpleimputer',
                  SimpleImputer(fill_value='MISSING', strategy='constant')),
                 ('onehotencoder',
                  OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
 Index(['origin'], dtype='object'))

##**Preprocessing Pipeline for Numerical Features**

In [ ]:
# Save list of numeric columns
num_cols = X_train.select_dtypes('number').columns
# Constructing numeric preprocesssing objects
num_imputer = SimpleImputer(strategy='median')
scaler = StandardScaler()
num_pipe = make_pipeline(num_imputer, scaler)
num_tuple = ('num',num_pipe, num_cols)
num_tuple

('num',
 Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                 ('standardscaler', StandardScaler())]),
 Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
        'model year'],
       dtype='object'))

##**Create Column Transformer**

In [ ]:
# Define a column transformer
preprocessor  = ColumnTransformer([num_tuple, cat_tuple],
                                  verbose_feature_names_out=False)

**Train Default Model (Using a model pipeline)
Our model pipeline will include the preprocessing object and the default model.**

In [ ]:
# Instantiate default random forest model
rf = RandomForestRegressor(random_state = 42)
# Model Pipeline
rf_pipe = make_pipeline(preprocessor, rf)

In [ ]:
# Fit the model pipeline on the training data only
rf_pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
       'model year'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(fill_value='MISSING',
                                                                                 strategy='constant')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['origin'], dtype='object'))],
                                   verbose_feature_names_out=False)),
                ('randomforestregressor',
                 RandomForestRegressor(random_state=42))])

**Evaluate**

In [ ]:
# Use custom function to evaluate default model
evaluate_regression(rf_pipe, X_train, y_train, X_test, y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 0.757
- MSE = 1.245
- RMSE = 1.245
- R^2 = 0.980

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 1.916
- MSE = 7.756
- RMSE = 7.756
- R^2 = 0.863

**Tune with GridSearchCV**

In [ ]:
# Parameters for tuning
rf_pipe.get_params()

{'memory': None,
 'steps': [('columntransformer',
   ColumnTransformer(transformers=[('num',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(strategy='median')),
                                                    ('standardscaler',
                                                     StandardScaler())]),
                                    Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
          'model year'],
         dtype='object')),
                                   ('cat',
                                    Pipeline(steps=[('simpleimputer',
                                                     SimpleImputer(fill_value='MISSING',
                                                                   strategy='constant')),
                                                    ('onehotencoder',
                                                     OneHotEncoder(handle_unknown='ignore',
                                                                   sparse_output=False))]),
                                    Index(['origin'], dtype='object'))],
                     verbose_feature_names_out=False)),
  ('randomforestregressor', RandomForestRegressor(random_state=42))],
 'transform_input': None,
 'verbose': False,
 'columntransformer': ColumnTransformer(transformers=[('num',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(strategy='median')),
                                                  ('standardscaler',
                                                   StandardScaler())]),
                                  Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
        'model year'],
       dtype='object')),
                                 ('cat',
                                  Pipeline(steps=[('simpleimputer',
                                                   SimpleImputer(fill_value='MISSING',
                                                                 strategy='constant')),
                                                  ('onehotencoder',
                                                   OneHotEncoder(handle_unknown='ignore',
                                                                 sparse_output=False))]),
                                  Index(['origin'], dtype='object'))],
                   verbose_feature_names_out=False),
 'randomforestregressor': RandomForestRegressor(random_state=42),
 'columntransformer__force_int_remainder_cols': True,
 'columntransformer__n_jobs': None,
 'columntransformer__remainder': 'drop',
 'columntransformer__sparse_threshold': 0.3,
 'columntransformer__transformer_weights': None,
 'columntransformer__transformers': [('num',
   Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                   ('standardscaler', StandardScaler())]),
   Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
          'model year'],
         dtype='object')),
  ('cat',
   Pipeline(steps=[('simpleimputer',
                    SimpleImputer(fill_value='MISSING', strategy='constant')),
                   ('onehotencoder',
                    OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
   Index(['origin'], dtype='object'))],
 'columntransformer__verbose': False,
 'columntransformer__verbose_feature_names_out': False,
 'columntransformer__num': Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median')),
                 ('standardscaler', StandardScaler())]),
 'columntransformer__cat': Pipeline(steps=[('simpleimputer',
                  SimpleImputer(fill_value='MISSING', strategy='constant')),
                 ('onehotencoder',
                  OneHotEncoder(handle_unknown='ignore', sparse_output=False))]),
 'columntransformer__num__memory': None,
 'columntransformer__num__steps': [('simpleimputer',
   SimpleImputer(strategy='median')),
  ('standardscaler', StandardScaler())],
 'columntransformer__num__transform_input': None,
 'columntransformer__num__verbose': False,
 'columntransformer__num__simpleimputer': SimpleImputer(strategy='median'),
 'columntransformer__num__standardscaler': StandardScaler(),
 'columntransformer__num__simpleimputer__add_indicator': False,
 'columntransformer__num__simpleimputer__copy': True,
 'columntransformer__num__simpleimputer__fill_value': None,
 'columntransformer__num__simpleimputer__keep_empty_features': False,
 'columntransformer__num__simpleimputer__missing_values': nan,
 'columntransformer__num__simpleimputer__strategy': 'median',
 'columntransformer__num__standardscaler__copy': True,
 'columntransformer__num__standardscaler__with_mean': True,
 'columntransformer__num__standardscaler__with_std': True,
 'columntransformer__cat__memory': None,
 'columntransformer__cat__steps': [('simpleimputer',
   SimpleImputer(fill_value='MISSING', strategy='constant')),
  ('onehotencoder',
   OneHotEncoder(handle_unknown='ignore', sparse_output=False))],
 'columntransformer__cat__transform_input': None,
 'columntransformer__cat__verbose': False,
 'columntransformer__cat__simpleimputer': SimpleImputer(fill_value='MISSING', strategy='constant'),
 'columntransformer__cat__onehotencoder': OneHotEncoder(handle_unknown='ignore', sparse_output=False),
 'columntransformer__cat__simpleimputer__add_indicator': False,
 'columntransformer__cat__simpleimputer__copy': True,
 'columntransformer__cat__simpleimputer__fill_value': 'MISSING',
 'columntransformer__cat__simpleimputer__keep_empty_features': False,
 'columntransformer__cat__simpleimputer__missing_values': nan,
 'columntransformer__cat__simpleimputer__strategy': 'constant',
 'columntransformer__cat__onehotencoder__categories': 'auto',
 'columntransformer__cat__onehotencoder__drop': None,
 'columntransformer__cat__onehotencoder__dtype': numpy.float64,
 'columntransformer__cat__onehotencoder__feature_name_combiner': 'concat',
 'columntransformer__cat__onehotencoder__handle_unknown': 'ignore',
 'columntransformer__cat__onehotencoder__max_categories': None,
 'columntransformer__cat__onehotencoder__min_frequency': None,
 'columntransformer__cat__onehotencoder__sparse_output': False,
 'randomforestregressor__bootstrap': True,
 'randomforestregressor__ccp_alpha': 0.0,
 'randomforestregressor__criterion': 'squared_error',
 'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': 1.0,
 'randomforestregressor__max_leaf_nodes': None,
 'randomforestregressor__max_samples': None,
 'randomforestregressor__min_impurity_decrease': 0.0,
 'randomforestregressor__min_samples_leaf': 1,
 'randomforestregressor__min_samples_split': 2,
 'randomforestregressor__min_weight_fraction_leaf': 0.0,
 'randomforestregressor__monotonic_cst': None,
 'randomforestregressor__n_estimators': 100,
 'randomforestregressor__n_jobs': None,
 'randomforestregressor__oob_score': False,
 'randomforestregressor__random_state': 42,
 'randomforestregressor__verbose': 0,
 'randomforestregressor__warm_start': False}

**Define Param Grid**

In [ ]:
# Define param grid with options to try
params = {'randomforestregressor__max_depth': [None,10,15,20],
          'randomforestregressor__n_estimators':[10,100,150,200],
          'randomforestregressor__min_samples_leaf':[2,3,4],
          'randomforestregressor__max_features':['sqrt','log2',None],
          'randomforestregressor__oob_score':[True,False],
          }

**Instantiate and Fit GridSearch**

In [ ]:
# Instantiate the gridsearch
gridsearch = GridSearchCV(rf_pipe, params, n_jobs=-1, cv = 3, verbose=1)
# Fit the gridsearch on training data
gridsearch.fit(X_train, y_train)

Fitting 3 folds for each of 288 candidates, totalling 864 fits

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('simpleimputer',
                                                                                          SimpleImputer(strategy='median')),
                                                                                         ('standardscaler',
                                                                                          StandardScaler())]),
                                                                         Index(['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration',
       'model year'],
      dtype='object')),
                                                                        ('cat',
                                                                         Pipeline(steps=[('simpleimputer',...
                                       ('randomforestregressor',
                                        RandomForestRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'randomforestregressor__max_depth': [None, 10, 15, 20],
                         'randomforestregressor__max_features': ['sqrt', 'log2',
                                                                 None],
                         'randomforestregressor__min_samples_leaf': [2, 3, 4],
                         'randomforestregressor__n_estimators': [10, 100, 150,
                                                                 200],
                         'randomforestregressor__oob_score': [True, False]},
             verbose=1)

**Obtain the best parameters**

In [ ]:
# Obtain best parameters
gridsearch.best_params_

{'randomforestregressor__max_depth': None,
 'randomforestregressor__max_features': None,
 'randomforestregressor__min_samples_leaf': 2,
 'randomforestregressor__n_estimators': 150,
 'randomforestregressor__oob_score': True}

**Define, Refit, and Evaluate the Best Model**

In [ ]:
# Define and refit best model
best_rf = gridsearch.best_estimator_
evaluate_regression(best_rf, X_train, y_train, X_test, y_test)

------------------------------------------------------------
Regression Metrics: Training Data
------------------------------------------------------------
- MAE = 0.988
- MSE = 2.268
- RMSE = 2.268
- R^2 = 0.964

------------------------------------------------------------
Regression Metrics: Test Data
------------------------------------------------------------
- MAE = 1.789
- MSE = 6.690
- RMSE = 6.690
- R^2 = 0.882